[tool.poetry]
name = "anno1800skyscraper"
version = "0.1.0"
description = ""
authors = ["Pascal Sado <pascal.sado@fys.uio.no>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
